FROM ubuntu:bionic

MAINTAINER PyLabs pylabs@allegro.pl

ENV DEBIAN_FRONTEND=noninteractive
ENV RALPH_DIR=/opt/ralph

RUN apt-get update && \
    apt-get -y install build-essential debhelper devscripts equivs dh-virtualenv \
    git libmysqlclient-dev python3 python3-dev libffi-dev nodejs npm git-buildpackage

COPY . $RALPH_DIR

WORKDIR $RALPH_DIR
CMD make -f Makefile.docker build-package
