# Generated by Django 2.2.28 on 2025-04-14 14:36

from django.db import migrations, transaction


def delete_scm_checks(apps, schema_editor):
    with transaction.atomic():
        ContentType = apps.get_model("contenttypes", "ContentType")
        SCMStatusCheck = apps.get_model("configuration_management", "SCMStatusCheck")
        Permission = apps.get_model("auth", "Permission")
        scm_content_type = ContentType.objects.filter(app_label='configuration_management', model='scmstatuscheck').first()
        if scm_content_type:
            SCMStatusCheck.objects.all().delete()
            Permission.objects.filter(content_type=scm_content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_management', '0003_scmstatuscheck_ok'),
    ]

    operations = [
        migrations.RunPython(delete_scm_checks, reverse_code=migrations.RunPython.noop),
    ]
