# Generated by Django 2.2.28 on 2025-04-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration_management', '0004_delete_scmstatuscheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SCMStatusCheck',
        ),
    ]
