# Generated by Django 4.2.25 on 2025-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixins_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
