# Generated by Django 2.0.13 on 2024-10-08 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("supports", "0010_auto_20240628_1207"),
        ("supports", "0010_auto_20241002_1122"),
    ]

    operations = []
