# Generated by Django 4.2.25 on 2025-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0013_alter_support_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseobjectssupport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='support',
            name='name',
            field=models.CharField(db_index=True, max_length=75, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='supporttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
