FROM ubuntu:14.04
MAINTAINER PyLabs pylabs@allegrogroup.com

# set UTF-8 locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN apt-get update && apt-get install -y mysql-server redis-server

ADD plugins.xml /root/plugins.xml

RUN echo test

RUN rm /root/plugins.xml
RUN apt-get purge -y mysql-server
RUN apt-get purge -y redis-server
