FROM ubuntu:14.04
MAINTAINER PyLabs pylabs@allegrogroup.com

# set UTF-8 locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# set paths
ENV RALPH_DIR=/opt/ralph
ENV SCRIPTS_PATH=/root

ENV PIP_WHEEL_DIR=/wheels
ENV PIP_FIND_LINKS=/wheels
ENV WHEELS_MOUNT=/wheels_mount

ADD docker/* $SCRIPTS_PATH/

# basic provisioning
RUN $SCRIPTS_PATH/provision.sh

# npm provisioning
ADD package.json $RALPH_DIR/package.json
RUN $SCRIPTS_PATH/provision_js.sh

# install basic requirements
WORKDIR $RALPH_DIR
RUN pip3 install wheel
ADD requirements $RALPH_DIR/requirements
RUN pip3 wheel -r requirements/prod_ldap.txt

# install JS dependencies
ADD src/ralph/static $RALPH_DIR/src/ralph/static
ADD gulpfile.js bower.json package.json $RALPH_DIR/
RUN $SCRIPTS_PATH/init_js.sh

ADD . $RALPH_DIR
RUN pip3 wheel --no-deps .

ENTRYPOINT rsync -rv $PIP_WHEEL_DIR $WHEELS_MOUNT

