FROM python:3.5-slim
MAINTAINER PyLabs pylabs@allegro.pl

# set UTF-8 locale
# RUN locale-gen en_US.UTF-8
# ENV LANG en_US.UTF-8
# ENV LANGUAGE en_US:en
# ENV LC_ALL en_US.UTF-8

# set paths
ENV RALPH_DIR=/opt/ralph
ENV RALPH_EXEC=ralph
ENV RALPH_LOGGING_FILE_PATH=/root/logs/runtime.log
ENV RALPH_STATIC=/root/static
ENV RALPH_DOCS=$RALPH_DIR/docs
ENV SCRIPTS_PATH=/root

RUN apt-key adv --keyserver  hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
RUN echo 'deb http://dl.bintray.com/vi4m/ralph wheezy main' >  /etc/apt/sources.list.d/vi4m_ralph.list

ADD docker/* $SCRIPTS_PATH/

RUN apt-get update && apt-get install -yy -o APT::Install-Recommends=false -o APT::Install-Suggests=false ralph-core

VOLUME $RALPH_DOCS
VOLUME $RALPH_STATIC
CMD $RALPH_EXEC runserver 0.0.0.0:8000
