.PHONY: cleanup

cleanup:
	rm -rf ./build 2>/dev/null 1>/dev/null

build-package: cleanup
	./scripts/build_deb_package.sh
	mkdir -p /volume/build
	cp ../*.deb /volume/build

build-snapshot-package: cleanup
	./scripts/generate_deb_changelog.sh
	./scripts/build_deb_package.sh
	mkdir -p /volume/build
	cp ../*.deb /volume/build

release-new-version:
	VERSION=$(shell ./get_version.sh generate) ./scripts/generate_deb_changelog.sh
	cp debian/changelog /volume/debian/changelog
