# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-09-24 11:55
from __future__ import unicode_literals

from django.db import migrations

import ralph.lib.polymorphic.fields


class Migration(migrations.Migration):
    dependencies = [
        ("networks", "0015_auto_20211115_1125"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="terminators",
            field=ralph.lib.polymorphic.fields.PolymorphicManyToManyField(
                blank=True, to="assets.BaseObject", verbose_name="network terminators"
            ),
        ),
    ]
