# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-09-25 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("networks", "0016_auto_20240621_1200"),
        ("networks", "0016_auto_20240924_1155"),
    ]

    operations = []
