# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-10-02 11:22
from __future__ import unicode_literals

from django.db import migrations

import ralph.lib.polymorphic.fields


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0012_auto_20211206_1347"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="base_objects",
            field=ralph.lib.polymorphic.fields.PolymorphicManyToManyField(
                blank=True,
                related_name="operations",
                to="assets.BaseObject",
                verbose_name="objects",
            ),
        ),
    ]
