# Generated by Django 4.2.25 on 2025-11-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0005_importedobjects_old_ci_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedobjects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
