# -*- mode: ruby -*-
unless Vagrant.has_plugin?("vagrant-reload")
    raise 'Please run vagrant plugin install vagrant-reload.'
end

Vagrant.configure(2) do |config|
    vm_user = "vagrant"
    ralph_dir = "/home/#{vm_user}/ralph"

    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = "ralph-dev"
    config.vm.synced_folder "../", ralph_dir, type: "rsync",
        rsync__exclude: ["../node_modules", "../.git", "../bower_components"],
        rsync__auto: true
    config.vm.provision :shell, path: "configure_kernel.sh", privileged: true
    config.vm.provision :reload
    config.vm.provision :shell, path: "provision.sh", privileged: false,
        env: { :RALPH_DIR => ralph_dir, :VM_USER => vm_user  },
        args: "do-provision"
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "forwarded_port", guest: 19360, host: 1936  # for Sublime Text Anaconda plugin
    config.vm.network "private_network", ip: "192.168.1.100"  # for DHCP server
    config.vm.provider :virtualbox do |vb|
        vb.name = "ralph_ng"
        vb.memory = 2048
        vb.cpus = 2
    end
end


begin
    load 'Vagrantfile.local'
rescue LoadError
    # ignore
end
