# -*- mode: ruby -*-

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ralph-dev"
  config.vm.synced_folder "../", "/home/vagrant/src/ralph"
  config.vm.provision :shell, path: "provision.sh", privileged: false
  config.vm.network "forwarded_port", guest: 8000, host: 8000
  config.vm.network "forwarded_port", guest: 19360, host: 1936  # for Sublime Text Anaconda plugin
  config.vm.provider :virtualbox do |vb|
    vb.name = "ralph_ng"
    vb.memory = 2048
    vb.cpus = 2
  end
end


begin
  load 'Vagrantfile.local'
rescue LoadError
  # ignore
end
