# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0031_auto_20200728_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                max_length=3,
                default="XXX",
                editable=False,
                choices=[
                    ("XXX", "---"),
                    ("AED", "AED"),
                    ("AFN", "AFN"),
                    ("ALL", "ALL"),
                    ("AMD", "AMD"),
                    ("ANG", "ANG"),
                    ("AOA", "AOA"),
                    ("ARS", "ARS"),
                    ("AUD", "AUD"),
                    ("AWG", "AWG"),
                    ("AZN", "AZN"),
                    ("BAM", "BAM"),
                    ("BBD", "BBD"),
                    ("BDT", "BDT"),
                    ("BGN", "BGN"),
                    ("BHD", "BHD"),
                    ("BIF", "BIF"),
                    ("BMD", "BMD"),
                    ("BND", "BND"),
                    ("BOB", "BOB"),
                    ("BOV", "BOV"),
                    ("BRL", "BRL"),
                    ("BSD", "BSD"),
                    ("BTN", "BTN"),
                    ("BWP", "BWP"),
                    ("BYN", "BYN"),
                    ("BYR", "BYR"),
                    ("BZD", "BZD"),
                    ("CAD", "CAD"),
                    ("CDF", "CDF"),
                    ("CHE", "CHE"),
                    ("CHF", "CHF"),
                    ("CHW", "CHW"),
                    ("CLF", "CLF"),
                    ("CLP", "CLP"),
                    ("CNY", "CNY"),
                    ("COP", "COP"),
                    ("COU", "COU"),
                    ("CRC", "CRC"),
                    ("CUC", "CUC"),
                    ("CUP", "CUP"),
                    ("CVE", "CVE"),
                    ("CZK", "CZK"),
                    ("DJF", "DJF"),
                    ("DKK", "DKK"),
                    ("DOP", "DOP"),
                    ("DZD", "DZD"),
                    ("EGP", "EGP"),
                    ("ERN", "ERN"),
                    ("ETB", "ETB"),
                    ("EUR", "EUR"),
                    ("FJD", "FJD"),
                    ("FKP", "FKP"),
                    ("GBP", "GBP"),
                    ("GEL", "GEL"),
                    ("GHS", "GHS"),
                    ("GIP", "GIP"),
                    ("GMD", "GMD"),
                    ("GNF", "GNF"),
                    ("GTQ", "GTQ"),
                    ("GYD", "GYD"),
                    ("HKD", "HKD"),
                    ("HNL", "HNL"),
                    ("HRK", "HRK"),
                    ("HTG", "HTG"),
                    ("HUF", "HUF"),
                    ("IDR", "IDR"),
                    ("ILS", "ILS"),
                    ("IMP", "IMP"),
                    ("INR", "INR"),
                    ("IQD", "IQD"),
                    ("IRR", "IRR"),
                    ("ISK", "ISK"),
                    ("JMD", "JMD"),
                    ("JOD", "JOD"),
                    ("JPY", "JPY"),
                    ("KES", "KES"),
                    ("KGS", "KGS"),
                    ("KHR", "KHR"),
                    ("KMF", "KMF"),
                    ("KPW", "KPW"),
                    ("KRW", "KRW"),
                    ("KWD", "KWD"),
                    ("KYD", "KYD"),
                    ("KZT", "KZT"),
                    ("LAK", "LAK"),
                    ("LBP", "LBP"),
                    ("LKR", "LKR"),
                    ("LRD", "LRD"),
                    ("LSL", "LSL"),
                    ("LTL", "LTL"),
                    ("LVL", "LVL"),
                    ("LYD", "LYD"),
                    ("MAD", "MAD"),
                    ("MDL", "MDL"),
                    ("MGA", "MGA"),
                    ("MKD", "MKD"),
                    ("MMK", "MMK"),
                    ("MNT", "MNT"),
                    ("MOP", "MOP"),
                    ("MRO", "MRO"),
                    ("MUR", "MUR"),
                    ("MVR", "MVR"),
                    ("MWK", "MWK"),
                    ("MXN", "MXN"),
                    ("MXV", "MXV"),
                    ("MYR", "MYR"),
                    ("MZN", "MZN"),
                    ("NAD", "NAD"),
                    ("NGN", "NGN"),
                    ("NIO", "NIO"),
                    ("NOK", "NOK"),
                    ("NPR", "NPR"),
                    ("NZD", "NZD"),
                    ("OMR", "OMR"),
                    ("PAB", "PAB"),
                    ("PEN", "PEN"),
                    ("PGK", "PGK"),
                    ("PHP", "PHP"),
                    ("PKR", "PKR"),
                    ("PLN", "PLN"),
                    ("PYG", "PYG"),
                    ("QAR", "QAR"),
                    ("RON", "RON"),
                    ("RSD", "RSD"),
                    ("RUB", "RUB"),
                    ("RWF", "RWF"),
                    ("SAR", "SAR"),
                    ("SBD", "SBD"),
                    ("SCR", "SCR"),
                    ("SDG", "SDG"),
                    ("SEK", "SEK"),
                    ("SGD", "SGD"),
                    ("SHP", "SHP"),
                    ("SLL", "SLL"),
                    ("SOS", "SOS"),
                    ("SRD", "SRD"),
                    ("SSP", "SSP"),
                    ("STD", "STD"),
                    ("SVC", "SVC"),
                    ("SYP", "SYP"),
                    ("SZL", "SZL"),
                    ("THB", "THB"),
                    ("TJS", "TJS"),
                    ("TMM", "TMM"),
                    ("TMT", "TMT"),
                    ("TND", "TND"),
                    ("TOP", "TOP"),
                    ("TRY", "TRY"),
                    ("TTD", "TTD"),
                    ("TVD", "TVD"),
                    ("TWD", "TWD"),
                    ("TZS", "TZS"),
                    ("UAH", "UAH"),
                    ("UGX", "UGX"),
                    ("USD", "USD"),
                    ("USN", "USN"),
                    ("UYI", "UYI"),
                    ("UYU", "UYU"),
                    ("UZS", "UZS"),
                    ("VEF", "VEF"),
                    ("VND", "VND"),
                    ("VUV", "VUV"),
                    ("WST", "WST"),
                    ("XAF", "XAF"),
                    ("XAG", "XAG"),
                    ("XAU", "XAU"),
                    ("XBA", "XBA"),
                    ("XBB", "XBB"),
                    ("XBC", "XBC"),
                    ("XBD", "XBD"),
                    ("XCD", "XCD"),
                    ("XDR", "XDR"),
                    ("XFO", "XFO"),
                    ("XFU", "XFU"),
                    ("XOF", "XOF"),
                    ("XPD", "XPD"),
                    ("XPF", "XPF"),
                    ("XPT", "XPT"),
                    ("XSU", "XSU"),
                    ("XTS", "XTS"),
                    ("XUA", "XUA"),
                    ("XYZ", "XYZ"),
                    ("YER", "YER"),
                    ("ZAR", "ZAR"),
                    ("ZMK", "ZMK"),
                    ("ZMW", "ZMW"),
                    ("ZWD", "ZWD"),
                    ("ZWL", "ZWL"),
                    ("ZWN", "ZWN"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="price",
            field=djmoney.models.fields.MoneyField(
                null=True,
                default=Decimal("0"),
                max_digits=15,
                decimal_places=2,
                default_currency="XXX",
            ),
        ),
    ]
