# Generated by Django 2.0.13 on 2024-06-21 12:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0036_auto_20240621_1200"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="asset",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="configurationclass",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="serviceenvironment",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
