# Generated by Django 2.0.13 on 2024-09-16 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0036_auto_20240904_1126"),
        ("assets", "0037_auto_20240621_1217"),
    ]

    operations = []
