# Generated by Django 4.2.23 on 2025-08-26 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0041_alter_asset_price_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configurationmodule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='configurationmodule',
            name='name',
            field=models.CharField(help_text='module name (ex. directory name in puppet)', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='\\w+')], verbose_name='name'),
        ),
    ]
