# Generated by Django 4.2.25 on 2026-04-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_alter_asset_hostname_alter_assetholder_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service / Component', 'verbose_name_plural': 'Services / Components'},
        ),
    ]
