# Generated by Django 4.2.25 on 2026-04-17 16:16

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0043_alter_asset_hostname_alter_assetholder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('port_count', models.PositiveIntegerField()),
                ('prefix', models.CharField(help_text='e.g. et-0/0/', max_length=64)),
                ('speed', models.CharField(choices=[(1, '10 Mbps'), (2, '100 Mbps'), (3, '1 Gbps'), (4, '10 Gbps'), (5, '40 Gbps'), (6, '100 Gbps'), (7, '25 Gbps'), (11, 'unknown speed')], max_length=32)),
                ('switch_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_templates', to='assets.assetmodel')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('speed', models.CharField(choices=[(1, '10 Mbps'), (2, '100 Mbps'), (3, '1 Gbps'), (4, '10 Gbps'), (5, '40 Gbps'), (6, '100 Gbps'), (7, '25 Gbps'), (11, 'unknown speed')], max_length=32)),
                ('base_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switchports_set', to='assets.baseobject')),
                ('remote_port', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.ethernet')),
            ],
            options={
                'unique_together': {('base_object', 'name')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
