# Generated by Django 4.2.25 on 2026-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0044_switchtemplate_switchport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switchport',
            name='speed',
            field=models.PositiveIntegerField(choices=[(1, '10 Mbps'), (2, '100 Mbps'), (3, '1 Gbps'), (4, '10 Gbps'), (5, '40 Gbps'), (6, '100 Gbps'), (7, '25 Gbps'), (11, 'unknown speed')], default=11, verbose_name='speed'),
        ),
        migrations.AlterField(
            model_name='switchtemplate',
            name='speed',
            field=models.PositiveIntegerField(choices=[(1, '10 Mbps'), (2, '100 Mbps'), (3, '1 Gbps'), (4, '10 Gbps'), (5, '40 Gbps'), (6, '100 Gbps'), (7, '25 Gbps'), (11, 'unknown speed')], default=11, verbose_name='speed'),
        ),
    ]
