# Generated by Django 4.2.30 on 2026-10-08 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0045_category_show_ports_in_visualization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='property_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.assetholder'),
        ),
    ]
