# Generated by Django 3.0.14 on 2025-04-15 13:34

from django.db import migrations, transaction


def delete_security_data(apps, schema_editor):
    with transaction.atomic():
        ContentType = apps.get_model("contenttypes", "ContentType")
        SecurityScan = apps.get_model("security", "SecurityScan")
        Vulnerability = apps.get_model("security", "Vulnerability")
        Permission = apps.get_model("auth", "Permission")
        security_scan_content_type = ContentType.objects.filter(app_label='security', model='securityscan').first()
        vulnerability_content_type = ContentType.objects.filter(app_label='security', model='vulnerability').first()

        if security_scan_content_type:
            SecurityScan.objects.all().delete()
            Permission.objects.filter(content_type=security_scan_content_type).delete()

        if vulnerability_content_type:
            Vulnerability.objects.all().delete()
            Permission.objects.filter(content_type=vulnerability_content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_vulnerability_display_name'),
    ]

    operations = [
        migrations.RunPython(delete_security_data, reverse_code=migrations.RunPython.noop),
    ]
