# Generated by Django 3.0.14 on 2025-04-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_delete_security_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerability',
            name='tags',
        ),
        migrations.DeleteModel(
            name='SecurityScan',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
    ]
