# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-05-06 11:33
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polymorphic_tests', '0002_somem2mmodel'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='polymorphicmodelbasetest',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='polymorphicmodeltest',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='polymorphicmodeltest2',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
