FROM ubuntu:bionic

ENV DEBIAN_FRONTEND=noninteractive

# Ralph configuration and paths
ARG RALPH_LOCAL_DIR="/var/local/ralph"
ARG RALPH_VERSION=""
ARG SNAPSHOT="0"
ENV PATH=/opt/ralph/ralph-core/bin/:$PATH
ENV RALPH_CONF_DIR="/etc/ralph"
ENV RALPH_LOCAL_DIR="$RALPH_LOCAL_DIR"
ENV RALPH_IMAGE_TMP_DIR="/tmp"

LABEL maintainer="Allegro.pl Sp. z o.o. opensource@allegro.pl"
LABEL authors="Allegro.pl Sp. z o.o. and Contributors opensource@allegro.pl"
LABEL description="Advanced Asset Management and DCIM system for data center and back office."
LABEL version="$RALPH_VERSION"

RUN echo 'Acquire::Retries "5";' > /etc/apt/apt.conf.d/80-retries

RUN apt-get clean && \
    apt-get update && \
    apt-get -y install --no-install-recommends ca-certificates

RUN sed 's@http://archive.ubuntu.com@https://ftp.uni-mainz.de/ubuntu@' -i /etc/apt/sources.list

RUN apt-get clean && \
    apt-get update && \
    apt-get -y install \
    apt-transport-https gnupg2 locales curl \
    python3 python3-dev python3-pip python3-setuptools git libldap2-dev libsasl2-dev \
    libffi-dev nodejs npm \
    libmysqlclient-dev=5.7.21-1ubuntu1 libmysqlclient20=5.7.21-1ubuntu1 && \
    rm -rf /var/lib/apt/lists/*

# set UTF-8 locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN mkdir -p $RALPH_LOCAL_DIR
COPY . $RALPH_LOCAL_DIR
WORKDIR $RALPH_LOCAL_DIR
RUN pip3 install -r $RALPH_LOCAL_DIR/requirements/dev.txt
