FROM nginx

ARG RALPH_VERSION=""

LABEL maintainer="Allegro.pl Sp. z o.o. opensource@allegro.pl"
LABEL authors="Allegro.pl Sp. z o.o. and Contributors opensource@allegro.pl"
LABEL description="Static files for Ralph DCIM served by Nginx HTTP server."
LABEL version="$RALPH_VERSION"

COPY contrib/docker/ralph-local-dev.conf.nginx /etc/nginx/conf.d/default.conf
