FROM ubuntu:jammy

LABEL maintainer="Allegro.pl Sp. z o.o. opensource@allegro.pl"
LABEL authors="Allegro.pl Sp. z o.o. and Contributors opensource@allegro.pl"
LABEL description="Helper image to build deb package for Ralph."

ARG GIT_USER_NAME='root'
ARG GIT_USER_EMAIL='root@localhost'

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash
ENV TERM=xterm
ENV EDITOR=nano
ENV RALPH_DIR=/opt/ralph

RUN apt-get update && \
    apt-get -y install build-essential debhelper devscripts equivs dh-virtualenv \
    libmysqlclient-dev libmysqlclient21 libldap2-dev libsasl2-dev \
    libwebp-dev libbrotli-dev liblzma-dev libjpeg-dev libssl-dev libkrb5-dev \
    libcom-err2 libkeyutils-dev libxau-dev libfreetype6-dev libpcre3-dev libselinux1-dev libtinfo-dev libpng-dev \
    python3.10-dev libffi-dev git-buildpackage vim-tiny git && \
    rm -rf /var/lib/apt/lists/* && \
    git config --global user.name "$GIT_USER_NAME" && \
    git config --global user.email "$GIT_USER_EMAIL"

RUN curl -sL https://deb.nodesource.com/setup_22.x | bash -
RUN apt-get update && apt-get install -y nodejs && node -v

COPY . $RALPH_DIR

WORKDIR $RALPH_DIR
ENTRYPOINT ["make", "-f", "Makefile.docker"]
