# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-06-21 10:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0013_auto_20190625_1239'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cloudflavor',
            managers=[
                ('polymorphic_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
