# Generated by Django 2.0.13 on 2024-06-21 12:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("virtual", "0014_auto_20240621_1009"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="cloudhost",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="cloudproject",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="virtualserver",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
