# Generated by Django 4.2.25 on 2025-11-17 14:04

from django.db import migrations, models
import ralph.lib.mixins.fields
import ralph.lib.transitions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0016_alter_virtualcomponent_base_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudhost',
            name='hostname',
            field=models.CharField(db_index=True, max_length=255, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='cloudimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cloudprovider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='virtualcomponent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='hostname',
            field=ralph.lib.mixins.fields.NullableCharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True, verbose_name='hostname'),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='sn',
            field=ralph.lib.mixins.fields.NullableCharField(blank=True, db_index=True, default=None, max_length=200, null=True, unique=True, verbose_name='SN'),
        ),
        migrations.AlterField(
            model_name='virtualserver',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'in use'), (3, 'to deploy'), (4, 'liquidated')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='virtualservertype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
