# Generated by Django 4.2.25 on 2025-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0017_alter_cloudhost_hostname_alter_cloudimage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudflavor',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='name'),
        ),
    ]
