# Generated by Django 4.2.25 on 2025-12-19 14:08

from django.db import migrations



def populate_cores_memory_disk_in_cloud_hosts(apps, schema_editor):
    # we don't use apps.get_model here because we wouldn't be able to utilize setters from models
    # and there is no schema change – the database had supported this already before
    from ralph.virtual.models import CloudHost
    for ch in CloudHost.polymorphic_objects.all():
        ch.disk = ch.cloudflavor.disk
        ch.memory = ch.cloudflavor.memory
        ch.cores = ch.cloudflavor.cores
        ch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0018_alter_cloudflavor_name'),
    ]

    operations = [
        migrations.RunPython(populate_cores_memory_disk_in_cloud_hosts),
    ]


