# Generated by Django 2.0.13 on 2024-06-21 12:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trade_marks", "0015_auto_20221020_1340"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="design",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="patent",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="trademark",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="utilitymodel",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
