# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-06-21 10:11
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("domains", "0007_auto_20200909_1012"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="domain",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
