# Generated by Django 2.0.13 on 2024-06-21 12:17

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("ssl_certificates", "0006_sslcertificate_certificate_repository"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sslcertificate",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
