# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-05-06 16:33
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deployment", "0006_auto_20211019_1456"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="prebootconfiguration",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="prebootfile",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="prebootitem",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
