# Generated by Django 2.0.13 on 2024-06-28 12:07

import django.db.models.deletion
from django.db import migrations

import ralph.lib.mixins.fields


class Migration(migrations.Migration):
    dependencies = [
        ("data_center", "0033_auto_20240621_1217"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseobjectcluster",
            name="base_object",
            field=ralph.lib.mixins.fields.BaseObjectForeignKey(
                limit_models=[
                    "data_center.Database",
                    "data_center.DataCenterAsset",
                    "virtual.CloudHost",
                    "virtual.VirtualServer",
                ],
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clusters",
                to="assets.BaseObject",
            ),
        ),
    ]
