# Generated by Django 2.2.28 on 2025-04-09 15:20

from django.db import migrations, transaction


def delete_vips(apps, schema_editor):
    with transaction.atomic():
        ContentType = apps.get_model("contenttypes", "ContentType")
        VIP = apps.get_model("data_center", "VIP")
        Permission = apps.get_model("auth", "Permission")
        vip_content_type = ContentType.objects.filter(app_label='data_center', model='vip').first()
        if vip_content_type:
            VIP.polymorphic_objects.all().delete()
            Permission.objects.filter(content_type=vip_content_type).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_vulnerability_display_name'),
        ('assets', '0039_merge_20241008_1243'),
        ('configuration_management', '0003_scmstatuscheck_ok'),
        ('licences', '0008_auto_20240628_1207'),
        ('operations', '0014_merge_20241008_1131'),
        ('virtual', '0015_auto_20240621_1217'),
        ('networks', '0017_merge_20240925_1101'),
        ('supports', '0011_merge_20241008_1131'),
        ('data_center', '0037_auto_20250321_1108'),
    ]

    operations = [
        migrations.RunPython(delete_vips, reverse_code=migrations.RunPython.noop),
    ]
