# Generated by Django 2.2.28 on 2025-04-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0015_auto_20240621_1217'),
        ('licences', '0008_auto_20240628_1207'),
        ('operations', '0014_merge_20241008_1131'),
        ('configuration_management', '0003_scmstatuscheck_ok'),
        ('assets', '0039_merge_20241008_1243'),
        ('supports', '0011_merge_20241008_1131'),
        ('security', '0008_vulnerability_display_name'),
        ('networks', '0017_merge_20240925_1101'),
        ('data_center', '0038_delete_vip_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VIP',
        ),
    ]
