# Generated by Django 4.2.25 on 2026-06-01 12:50

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0041_alter_accessory_id_alter_baseobjectcluster_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=75, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='description')),
                ('data_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rack_modules', to='data_center.datacenter', verbose_name='data center')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.AddField(
            model_name='rack',
            name='rack_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='data_center.rackmodule'),
        ),
    ]
