# Generated by Django 4.2.25 on 2026-06-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0041_alter_accessory_id_alter_baseobjectcluster_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
