# Generated by Django 4.2.25 on 2026-06-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0042_rackmodule_rack_rack_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
