# Generated by Django 4.2.25 on 2026-06-16 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0043_rack_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenterasset',
            name='connections',
        ),
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
