# Generated by Django 4.2.30 on 2026-08-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0044_remove_datacenterasset_connections_delete_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterasset',
            name='metadata',
            field=models.JSONField(blank=True, default=None, help_text='Additional JSON data for this asset.', null=True, verbose_name='metadata'),
        ),
    ]
