# Generated by Django 4.2.30 on 2026-08-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0045_datacenterasset_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterasset',
            name='production_year',
            field=models.PositiveSmallIntegerField(db_index=True, null=True),
        ),
    ]
