# Generated by Django 2.0.13 on 2024-06-21 12:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back_office", "0023_auto_20240223_1018"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="backofficeasset",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
