# Generated by Django 4.2.23 on 2025-08-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0024_auto_20240621_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='external_depot_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
