# Generated by Django 4.2.25 on 2025-11-17 14:04

from django.db import migrations, models
import ralph.lib.transitions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0027_alter_backofficeasset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backofficeasset',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'in progress'), (3, 'waiting for release'), (4, 'in use'), (5, 'loan'), (6, 'damaged'), (7, 'liquidated'), (8, 'in service'), (9, 'installed'), (10, 'free'), (11, 'reserved'), (12, 'sale'), (13, 'loan in progress'), (14, 'return in progress'), (15, 'to find'), (16, 'sent'), (17, 'to buyout'), (18, 'in use team'), (19, 'in use test'), (20, 'in progress team'), (21, 'in progress test'), (22, 'quarantine'), (23, 'refurbished'), (24, 'reserved to order'), (25, 'replacement'), (26, 'in maintenance'), (27, 'not returned [EL]'), (28, 'taken for disposal'), (29, 'in use (mgmt excluded)'), (30, 'in use test (mgmt excluded)'), (31, 'in use team (mgmt excluded)'), (32, 'in use (update excluded)'), (33, 'in use test (update excluded)'), (34, 'in use team (update excluded)')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='officeinfrastructure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
