# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-06-21 10:09
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0008_auto_20200909_1322"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="polymorphictestmodel",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
