# Generated by Django 2.0.13 on 2024-09-18 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0014_auto_20240628_1213"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Manufacturer",
            new_name="TestManufacturer",
        ),
    ]
