# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2024-06-21 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access_cards", "0005_auto_20211022_1038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesszone",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="accesszone",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="accesszone",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
