# Generated by Django 4.2.25 on 2025-11-17 14:04

from django.db import migrations, models
import ralph.lib.transitions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('access_cards', '0006_auto_20240621_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accesscard',
            name='status',
            field=ralph.lib.transitions.fields.TransitionField(choices=[(1, 'new'), (2, 'in progress'), (3, 'lost'), (4, 'damaged'), (5, 'in use'), (6, 'free'), (7, 'return in progress'), (8, 'liquidated'), (9, 'reserved')], db_index=True, default=1, help_text='Access card status'),
        ),
        migrations.AlterField(
            model_name='accesszone',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
