# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2024-05-06 16:33
from __future__ import unicode_literals

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("licences", "0006_auto_20200909_1115"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="licence",
            managers=[
                ("polymorphic_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
