# Generated by Django 4.2.30 on 2026-07-21 13:58

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_center', '0044_remove_datacenterasset_connections_delete_connection'),
        ('networks', '0018_alter_discoveryqueue_id_alter_ipaddress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('local_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_address_reservation', to='networks.ipaddress')),
                ('remote_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_address_reservation', to='networks.ipaddress')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('rack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rack_configuration', to='data_center.rack')),
            ],
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RackSwitchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, help_text='Switch role e.g. eth1, eth2, mgmt', max_length=255)),
                ('backend_validation', models.BooleanField(default=True, help_text='When enabled, netmaker backend validation is fetched and the netmaker column is shown for this switch in the switchport grid.')),
                ('rack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='switchports.rackconfiguration')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_switches', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('rack_configuration', 'label')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SwitchportRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], db_index=True, default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, help_text='Per-switch counts and errors collected during the refresh.', null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('rack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_jobs', to='switchports.rackconfiguration')),
            ],
            options={
                'ordering': ('-created',),
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('label', models.CharField(db_index=True, max_length=255)),
                ('address_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='switchports.addressreservation')),
                ('data_center_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('label', 'data_center_asset')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConnectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='switchports.connection')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectionmember', to='switchports.port')),
            ],
        ),
        migrations.CreateModel(
            name='RackSwitchConfigurationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_center_asset', models.ForeignKey(help_text='The server whose connection deviates from the column default.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
                ('rack_switch_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='switchports.rackswitchconfiguration')),
                ('switch', models.ForeignKey(help_text='The alternate switch this server connects to for this column.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('rack_switch_configuration', 'data_center_asset')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackendValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('port_label', models.CharField(help_text='Switch port label, e.g. 0/0/20', max_length=255)),
                ('status', models.CharField(choices=[('SWITCH_NOT_FOUND', 'Switch not found in backend'), ('PORT_NOT_FOUND', 'Port not found on switch'), ('ASSET_FOUND', 'Asset found on port'), ('ASSET_CONFLICT', 'Conflicting assets reported by backend')], max_length=20)),
                ('remote_hostname', models.CharField(blank=True, default='', help_text='Raw hostname reported by LLDP (even if not matched to a Ralph asset)', max_length=255)),
                ('oper_status', models.CharField(blank=True, default='', help_text='Operational status reported by the backend (up/down/unknown)', max_length=20)),
                ('admin_status', models.CharField(blank=True, default='', help_text='Administrative status reported by the backend (up/down/unknown)', max_length=20)),
                ('speed', models.IntegerField(blank=True, help_text='Interface speed in Mbps', null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='Full interface payload reported by the backend (netmaker)', null=True)),
                ('rack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='switchports.rackconfiguration')),
                ('remote_asset', models.ForeignKey(blank=True, help_text='The asset found on the other side of this port (if resolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_center.datacenterasset')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('rack_configuration', 'switch', 'port_label')},
            },
        ),
    ]
