# Generated by Django 4.2.25 on 2026-05-21 14:53

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_center', '0041_alter_accessory_id_alter_baseobjectcluster_id_and_more'),
        ('networks', '0018_alter_discoveryqueue_id_alter_ipaddress_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('local_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_address_reservation', to='networks.ipaddress')),
                ('remote_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remote_address_reservation', to='networks.ipaddress')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('label', models.CharField(max_length=255)),
                ('address_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='switchports.addressreservation')),
                ('data_center_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('label', 'data_center_asset')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ConnectionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='switchports.connection')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connectionmember', to='switchports.port')),
            ],
        ),
    ]
