# Generated by Django 4.2.25 on 2026-06-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0043_rack_active'),
        ('switchports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('eth1_default_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eth1_default', to='data_center.datacenterasset')),
                ('eth2_default_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eth2_default', to='data_center.datacenterasset')),
                ('mgmt_default_switch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgmt_default', to='data_center.datacenterasset')),
                ('rack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rack_configuration', to='data_center.rack')),
            ],
        ),
    ]
