# Generated by Django 4.2.30 on 2026-07-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0044_remove_datacenterasset_connections_delete_connection'),
        ('switchports', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='backendvalidationresult',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='backendvalidationresult',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='data_center.datacenterasset'),
        ),
        migrations.AlterUniqueTogether(
            name='backendvalidationresult',
            unique_together={('switch', 'port_label')},
        ),
    ]
