# Generated by Django 4.2.30 on 2026-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchports', '0002_alter_backendvalidationresult_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backendvalidationresult',
            name='rack_configuration',
        ),
    ]
