# Generated by Django 4.2.25 on 2026-07-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0044_remove_datacenterasset_connections_delete_connection'),
        ('switchports', '0002_rackconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rackconfiguration',
            name='eth1_default_switch',
        ),
        migrations.RemoveField(
            model_name='rackconfiguration',
            name='eth2_default_switch',
        ),
        migrations.RemoveField(
            model_name='rackconfiguration',
            name='mgmt_default_switch',
        ),
        migrations.CreateModel(
            name='RackSwitchConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, help_text='Switch role e.g. eth1, eth2, mgmt')),
                ('rack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='switchports.rackconfiguration')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_switches', to='data_center.datacenterasset')),
            ],
        ),
    ]
