# Generated by Django 4.2.30 on 2026-09-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0046_alter_datacenterasset_production_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('switchports', '0003_remove_backendvalidationresult_rack_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('label', models.CharField()),
                ('status', models.CharField(choices=[('same_asset', 'Same Asset'), ('asset_mismatch', 'Asset Mismatch'), ('port_missing', 'Port Missing'), ('netmaker_empty', 'Netmaker Empty'), ('ralph_empty', 'Ralph Empty'), ('not_validated', 'Not Validated')], max_length=255)),
                ('netmaker_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
                ('ralph_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
            ],
            options={
                'verbose_name': 'Switchport diff',
                'verbose_name_plural': 'Switchport diff entries',
                'unique_together': {('switch', 'label')},
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DiffStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stamp', to='switchports.diffentry')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
