# Generated by Django 4.2.25 on 2026-07-02 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0044_remove_datacenterasset_connections_delete_connection'),
        ('switchports', '0003_remove_rackconfiguration_eth1_default_switch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackswitchconfiguration',
            name='label',
            field=models.TextField(db_index=True, help_text='Switch role e.g. eth1, eth2, mgmt'),
        ),
        migrations.AlterUniqueTogether(
            name='rackswitchconfiguration',
            unique_together={('rack_configuration', 'label')},
        ),
        migrations.CreateModel(
            name='BackendValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('port_label', models.CharField(help_text='Switch port label, e.g. 0/0/20', max_length=255)),
                ('status', models.CharField(choices=[('SWITCH_NOT_FOUND', 'Switch not found in backend'), ('PORT_NOT_FOUND', 'Port not found on switch'), ('ASSET_FOUND', 'Asset found on port'), ('ASSET_CONFLICT', 'Conflicting assets reported by backend')], max_length=20)),
                ('remote_hostname', models.CharField(blank=True, default='', help_text='Raw hostname reported by LLDP (even if not matched to a Ralph asset)', max_length=255)),
                ('rack_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='switchports.rackconfiguration')),
                ('remote_asset', models.ForeignKey(blank=True, help_text='The asset found on the other side of this port (if resolved)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='data_center.datacenterasset')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data_center.datacenterasset')),
            ],
            options={
                'unique_together': {('rack_configuration', 'switch', 'port_label')},
            },
        ),
    ]
