# Generated by Django 4.2.25 on 2026-07-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchports', '0009_backfill_rack_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='label',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rackswitchconfiguration',
            name='label',
            field=models.TextField(db_index=True, help_text='Switch role e.g. eth1, eth2, mgmt', max_length=255),
        ),
    ]
