# Generated by Django 4.2.25 on 2026-07-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchports', '0010_alter_port_label_alter_rackswitchconfiguration_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackconfiguration',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
