# Generated by Django 4.2.25 on 2026-07-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchports', '0011_alter_rackconfiguration_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackswitchconfiguration',
            name='label',
            field=models.TextField(help_text='Switch role e.g. eth1, eth2, mgmt', max_length=255),
        ),
    ]
