# Generated by Django 4.2.30 on 2026-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('switchports', '0012_alter_rackswitchconfiguration_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rackswitchconfiguration',
            name='label',
            field=models.CharField(db_index=True, help_text='Switch role e.g. eth1, eth2, mgmt', max_length=255),
        ),
    ]
