# Generated by Django 3.1.14 on 2025-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ralphuser_service_visibility_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ralphuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
