name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify clean tag
        run: make verify-clean-tag
      - name: Build
        run: make build-package
      - name: Install packagecloud CLI
        run: sudo gem install package_cloud
      - name: Publish deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: package_cloud push allegro/ralph/ubuntu/bionic build/*.deb
      - name: Publish docker
        env:
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASS }}
        run: make publish-docker-image
