name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify github ref
        run: |
          TAG=$(echo "$GITHUB_REF" | grep -E -o '^refs\/tags\/[0-9]{8}\.[0-9]+$' || true)
          if [[ -z "$TAG" ]]; then
              >&2 echo "The \$GITHUB_REF does not point to a properly named tag."
              exit 1
          fi
      - name: Install and configure Mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - name: Mise install tools
        run: mise install uv python
      - name: Publish docker
        env:
          RETRY_COUNT: 3
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
          export RALPH_VERSION=${GITHUB_REF#refs/*/}
          until [ "$RETRY_COUNT" -le 0 ]
            do
              mise run publish-docker-image && break
              RETRY_COUNT=$((RETRY_COUNT-1))
              echo "==== Publish docker failed. Remaining retries: $RETRY_COUNT ===="
            done
          docker logout
