name: Publish

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify clean tag
        run: make verify-clean-tag
      - name: Build
        run: make build-package
      - name: Install packagecloud CLI
        run: sudo gem install package_cloud
      - name: Publish deb
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
        run: package_cloud push allegro/ralph/ubuntu/bionic build/*.deb
      - name: Build docker prod
        run: |
          docker build -f docker/Dockerfile-prod \
            --build-arg RALPH_VERSION=${GITHUB_REF#refs/*/} \
            -t allegro/ralph:${GITHUB_REF#refs/*/} \
            -t allegro/ralph:latest \
            .
      - name: Build docker static
        run: |
          docker build -f docker/Dockerfile-static \
            --build-arg RALPH_VERSION=${GITHUB_REF#refs/*/} \
            -t allegro/ralph-static-nginx:${GITHUB_REF#refs/*/} \
            -t allegro/ralph-static-nginx:latest \
            .
      - name: Docker login
        run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login --username allegro --password-stdin
      - name: Publish docker prod
        run: |
          docker push allegro/ralph:${GITHUB_REF#refs/*/}
          docker push allegro/ralph:latest
      - name: Publish docker static
        run: |
          docker push allegro/ralph-static-nginx:${GITHUB_REF#refs/*/}
          docker push allegro/ralph:latest
      - name: Docker logout
        run: docker logout
